package p1_9;
/* Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by 
 * adding the previous two terms. By starting with 1 and 2, t
 * he first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values 
 * do not exceed four million, find the sum of the even-valued terms.
 * */
public class Problem2 {

	public static void main(String args[])
	{
		int prev = 1;
		int curr = 2;
		int tmp = 0;
		int sum = 0;
		while(curr <= 4000000)
		{
			if(curr % 2 == 0)
			{
				sum += curr;
			}
			tmp = prev + curr;
			prev = curr;
			curr = tmp;
		}
		System.out.println(sum);
	}
	
}
